# Generated by Django 5.2.4 on 2025-07-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advacned', 'Advacned')])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pub_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
