# Generated by Django 5.2.4 on 2025-08-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.png', upload_to='courses'),
        ),
    ]
